version: '3'

services:
  php:
    container_name: masmapi_php
    restart: "always"
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./application:/var/www/symfony
      - ./application/.messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
    command: sh -c "composer install && bin/console doctrine:schema:update --force --env=prod && php-fpm"
    depends_on:
      - database
  nginx:
    container_name: masmapi_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./application:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/502.html:/var/www/502.html
    depends_on:
      - php
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
